### ISSUE TITLE
Storageadapter fails on Linux amd-64 machine

### ISSUE THREAD

**Issue by cgritton** [Azure/pcs-storage-adapter-java#53] opened 2018-04-02 16:54 UTC
# Type of issue 

- [ x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Taking the current repository and running a docker-compose up (per the instructions for a local run) fails.  The pattern of failures differs a bit from run to run but, consistently, the storageadapter fails. 

Specifically, the ERROR message says: "c.m.a.i.s.s.w.DocumentClientFactory - Error creating database: pcs-storage" and it is followed immediately in the log with a warning that says: "c.m.a.d.i.ServiceJNIWrapper - 'Linux' with 'amd64' system is not compatible with native library. JNI not loaded.".  

There are subsequent errors as well but I assume they flow from this one.

...

# Steps to reproduce 

1. Run docker-compose up on the repository following the instructions (after pcs login, pcs -s local, and copying the printed env variables to the .env file
2. Use docker-compose logs to check the storageadapter status

# Expected behavior 
The pre-configured system code runs without errors but, specifically with the storage adapter.

# Current behavior 
The pre-configured system code fails in several spots but seemingly with this root error.

# Known workarounds 
None

# Possible solution 

# Context and Environment
* Operating System: Linux Ubuntu 16.04 LTS
* GitHub branch: Master
* Java SDK: OpenJDK version 1.8

# Code to reproduce the bug 

No special code required - fails with Master code as is.  Relevant log snippet from storageadapter run shown below:

Attaching to local_storageadapter_1
storageadapter_1    | [info] a.e.s.Slf4jLogger - Slf4jLogger started
storageadapter_1    | [info] o.h.v.i.u.Version - HV000001: Hibernate Validator 5.4.1.Final
storageadapter_1    | [warn] o.h.v.m.ParameterMessageInterpolator - HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
storageadapter_1    | [info] play.api.Play - Application started (Prod)
storageadapter_1    | [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9022
storageadapter_1    | [info] c.m.a.d.DocumentClient - Initializing DocumentClient with serviceEndpoint [https://documentdb-ve2vr.documents.azure.com:443/], ConnectionPolicy [ConnectionPolicy [requestTimeout=60, mediaRequestTimeout=300, connectionMode=Gateway, mediaReadMode=Buffered, maxPoolSize=100, idleConnectionTimeout=60, userAgentSuffix=, retryOptions=com.microsoft.azure.documentdb.RetryOptions@5e17f4a7, enableEndpointDiscovery=true, preferredLocations=null]], ConsistencyLevel [Session]
storageadapter_1    | [info] c.m.a.d.DocumentClient - Initializing DocumentClient with serviceEndpoint [https://documentdb-ve2vr.documents.azure.com:443/], ConnectionPolicy [ConnectionPolicy [requestTimeout=60, mediaRequestTimeout=300, connectionMode=Gateway, mediaReadMode=Buffered, maxPoolSize=100, idleConnectionTimeout=60, userAgentSuffix=, retryOptions=com.microsoft.azure.documentdb.RetryOptions@5e17f4a7, enableEndpointDiscovery=true, preferredLocations=null]], ConsistencyLevel [Session]
storageadapter_1    | [info] c.m.a.d.DocumentClient - Initializing DocumentClient with serviceEndpoint [https://documentdb-ve2vr.documents.azure.com:443/], ConnectionPolicy [ConnectionPolicy [requestTimeout=60, mediaRequestTimeout=300, connectionMode=Gateway, mediaReadMode=Buffered, maxPoolSize=100, idleConnectionTimeout=60, userAgentSuffix=, retryOptions=com.microsoft.azure.documentdb.RetryOptions@5e17f4a7, enableEndpointDiscovery=true, preferredLocations=null]], ConsistencyLevel [Session]
storageadapter_1    | [error] c.m.a.i.s.s.w.DocumentClientFactory - Error creating database: pcs-storage
storageadapter_1    | [warn] c.m.a.d.i.ServiceJNIWrapper - 'Linux' with 'amd64' system is not compatible with native library. JNI not loaded.
storageadapter_1    | [error] c.m.a.i.s.s.DocDBKeyValueContainer - Error reading document: /dbs/pcs-storage/colls/pcs-storage/docs/solution-settings.seedmutex
storageadapter_1    | [error] c.m.a.i.s.s.DocDBKeyValueContainer - Error reading document: /dbs/pcs-storage/colls/pcs-storage/docs/solution-settings.seedcompleted
storageadapter_1    | [error] c.m.a.i.s.s.DocDBKeyValueContainer - Error reading document: /dbs/pcs-storage/colls/pcs-storage/docs/rules.default_chiller_pressure_high
storageadapter_1    | [error] c.m.a.i.s.s.DocDBKeyValueContainer - Error reading document: /dbs/pcs-storage/colls/pcs-storage/docs/cache.twin
storageadapter_1    | [info] p.c.s.AkkaHttpServer - Stopping server...
storageadapter_1    | [info] a.a.CoordinatedShutdown - Starting coordinated shutdown from JVM shutdown hook
storageadapter_1    | [info] a.e.s.Slf4jLogger - Slf4jLogger started
storageadapter_1    | [info] o.h.v.i.u.Version - HV000001: Hibernate Validator 5.4.1.Final
storageadapter_1    | [warn] o.h.v.m.ParameterMessageInterpolator - HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
storageadapter_1    | [info] play.api.Play - Application started (Prod)
storageadapter_1    | [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9022
storageadapter_1    | [info] c.m.a.d.DocumentClient - Initializing DocumentClient with serviceEndpoint [https://documentdb-ve2vr.documents.azure.com:443/], ConnectionPolicy [ConnectionPolicy [requestTimeout=60, mediaRequestTimeout=300, connectionMode=Gateway, mediaReadMode=Buffered, maxPoolSize=100, idleConnectionTimeout=60, userAgentSuffix=, retryOptions=com.microsoft.azure.documentdb.RetryOptions@706f22c9, enableEndpointDiscovery=true, preferredLocations=null]], ConsistencyLevel [Session]
storageadapter_1    | [warn] c.m.a.d.i.ServiceJNIWrapper - 'Linux' with 'amd64' system is not compatible with native library. JNI not loaded.

```

**Comment by ppathan** [comment] 2018-04-19 16:04
Closing this issue based on comment above. Opening a doc bug to update our documentation if it is needed.

**Closed by ppathan** 2018-04-19 16:04 UTC

**Comment by oussamaoueskantena** [comment] 2018-06-25 08:48
Hello, 

I have the same problem since I've tried to explore my Cosmos DB, now I can't do anything and when I do : 
"docker logs [StorageAdapterID] " I have found this logs:
[warn] c.m.a.d.i.ServiceJNIWrapper - 'Linux' with 'amd64' system is not compatible with native library. JNI not loaded.
[error] c.m.a.i.s.s.DocDBKeyValueContainer - Error reading document: /dbs/pcs-storage/colls/pcs-storage/docs/solution-settings.theme


Can anyone help me?? thnx

**Comment by sushilraje** [comment] 2018-06-25 20:36
Hi oussamaoueskantena,

Can you post the exact steps to reproduce? Also, can you post the all the logs from the container?
I tried with Ubuntu 16.04 and RHEL, it worked on both.

To debug further, I would require following details as well. 

1. Linux flavour & version
2. docker version
3. docker image details
4. Cosmos DB API
